/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package MVC.view.LoginAndRegister.Form;

import MVC.view.BINUtils;
import MVC.view.Message.GlassPanePopup;
import MVC.view.Message.MessageNotconnect;
import MVC.view.Message.MessageRegister;
import MVC.view.UserInfor;
import java.util.List;

/**
 *
 * @author ssopt
 */
public class Register extends PanelCustom {

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        password1 = new MVC.view.LoginAndRegister.Swing.Password();
        email = new MVC.view.LoginAndRegister.Swing.TextField();
        button1 = new MVC.view.LoginAndRegister.Swing.Button();
        user = new MVC.view.LoginAndRegister.Swing.TextField();

        setBackground(new java.awt.Color(76, 76, 76));
        setForeground(new java.awt.Color(234, 227, 227));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(243, 238, 238));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SIGN UP");

        password1.setForeground(new java.awt.Color(242, 242, 242));
        password1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        password1.setHint("Password");
        password1.setSelectedTextColor(new java.awt.Color(245, 238, 238));

        email.setForeground(new java.awt.Color(255, 255, 255));
        email.setCaretColor(new java.awt.Color(204, 204, 204));
        email.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        email.setHint("Email");
        email.setSelectedTextColor(new java.awt.Color(241, 235, 235));
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });

        button1.setBackground(new java.awt.Color(80, 161, 242));
        button1.setForeground(new java.awt.Color(255, 255, 255));
        button1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        button1.setLabel("Sign Up");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        user.setForeground(new java.awt.Color(242, 242, 242));
        user.setCaretColor(new java.awt.Color(204, 204, 204));
        user.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        user.setHint("Username");
        user.setSelectedTextColor(new java.awt.Color(241, 235, 235));
        user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                    .addComponent(password1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(email, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(button1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(user, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(password1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        String userName = user.getText().toString().trim();
        String mail = email.getText().toString().trim();
        String pass = String.valueOf(password1.getPassword()).trim();
        List<UserInfor> list = BINUtils.read("UsersInfor.DAT");
        boolean kt = true;
        for (UserInfor it : list){
            if (it.getName().equals(userName) && it.getEmail().equals(mail) ){
                kt = false;
                break;
            }
        }
        
        if (kt == true){
            list.add(new UserInfor(userName,mail, pass));
            BINUtils.write("UsersInfor.DAT",list);
        }
        user.setText("");
        email.setText("");
        password1.setText("");
    }//GEN-LAST:event_button1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private MVC.view.LoginAndRegister.Swing.Button button1;
    private MVC.view.LoginAndRegister.Swing.TextField email;
    private javax.swing.JLabel jLabel1;
    private MVC.view.LoginAndRegister.Swing.Password password1;
    private MVC.view.LoginAndRegister.Swing.TextField user;
    // End of variables declaration//GEN-END:variables
}
